### ISSUE TITLE
Concatenates When Post is Sent

### ISSUE THREAD

**Issue by tghilardi** [tovic/tags-input-beautifier#2]
tags concatenate when you send a post request to the same page.

eg: test,test2 outputs testtest2 as one tag instead of two.

**Comment by tovic** [comment]
Yes, this plugin only for visualization, in the hope that, if JavaScript is disabled, user can keep adding tags as comma&ndash;separated list of words. You can later explode it in the backend:

~~~ .php
$_POST['tags'] = explode(', ', $_POST['tags']);
~~~

**Comment by tovic** [comment]
OH, so the tags becomes `testtest2`.

**Comment by tovic** [comment]
Do you have any screenshot or examples about this bug? I want to close this.
