### ISSUE TITLE
Stay in Input After Creating Tag

### ISSUE THREAD

**Issue by lorraineS** [tovic/tags-input-beautifier#4]
Nothing planned for the "tab" key to remain in input ? Thanks 👍

**Comment by tovic** [comment]
No. It is for accessibility. Imagine you are a user without a mouse. How can you move to another field without the tab key?

**Comment by lorraineS** [comment]
I assume that all users have one. But ok :)

**Comment by tovic** [comment]
I am probably one of those who still use the tab key to move from _username_ field to _password_ field when log in even when I have a mouse ;)

**Comment by lorraineS** [comment]
I understand. But if you want to add 3 tags in your search field and you don't have a mouse, you will have to browse the DOM 3 times by navigating with tab. Chaotic ...

**Comment by tovic** [comment]
What&rsquo;s your case for the usage of this project in the work? I am curious on what the reason behind this behaviour. Similar plugins out there also simply disable the space key, just like what GitHub does.

**Comment by tovic** [comment]
I am now thinking about adding such option to list all forbidden characters which when typed, it will simply trigger the tag addition. Something like this:

~~~ .js
new TIB(node, {escape: [',', ' ', '\t']});
~~~

**Comment by lorraineS** [comment]
That seems to be a great idea.

**Comment by tovic** [comment]
You can now disable the tab key, by adding `\t` to the `escape` list:

~~~ .js
// disable `comma`, `enter` and `tab` key
new TIB(node, {escape: [',', '\n', '\t']});
~~~
