### ISSUE TITLE
cannot get the \n to escape in a multi-field form with submit button

### ISSUE THREAD

**Issue by aliaa-marxlabs** [tovic/tags-input-beautifier#7]
Hi, even with the following config, pressing the enter key at my tags input field submits the form without throwing error on the required fields (which has been left empty when i'm testing the tags). please advise. the issue is happening in chrome 58, ie 11 and ff 53

``` html
<form name="regform" action="page2_form.php" method="post" class="rectangle-copy">
            <label class="title">Business Name</label>
            <input class="rectangle-2-copy" name="business_name" type="text" required>
            <label class="title">Industry</label>
            <input class="rectangle-2-copy" name="industry" type="text">
            
            <div class="form-group form-row2">
                <label class="title">Describe your business in keywords</label>
                    <div style="position:relative; display:inline-block; height:10px">
                        <div class="tooltip-custom" rel="tooltip"> 
                    <i class="fa fa-question-circle" style="color: #B2B0B3;"></i>
                    <span class="tooltiptext">Press enter to insert keyword. Max 10 keywords</span>
                    </div>
                    </div>
                <div id="tagsinput">
                    <input type="text" name="tags"/>
                </div>
            </div>
 <input class="rectangle-copy-7" type="submit" value="Next" />
 </form>
```

``` js
var tags = new TIB(document.querySelector('input[name="tags"]'), {
                join: ', ', // Tags joiner of the output value
                max: 10, // Maximum tags allowed
                escape: [',','\n'],
                alert: true,
                text: ['Delete \u201C%s\u201D', 'Duplicate \u201C%s\u201D'],
                classes: ['tags', 'tag', 'tags-input', 'tags-output', 'tags-view'], // HTML classes
                });`
```

**Comment by tovic** [comment]
Just add `required` attribute to the input.

**Comment by aliaa-marxlabs** [comment]
hi...what i meant was, the enter key created the tag, but also immediately submits the form instead of staying on the field for the next tag/next user action. from my html, you'll see i have other required fields before the tags field and i don't intend on making the tags field a required input currently

**Comment by tovic** [comment]
Will check this next time. Your form, using AJAX? Is there any event handler to the form that hijack the `Enter` key?

**Comment by aliaa-marxlabs** [comment]
not using ajax..and there is no event handler for enter key. i tried adding an event handler for enter key (preventDefault when user press enter), but pressing enter at the tags field still submitted the form, whereas preventDefault, etc works fine when pressing enter at other fields. :(

**Comment by aliaa-marxlabs** [comment]
i've tried with simpler form, full file below (originally html, i've changed it changed to .txt for upload purposes). pressing the enter key at the tags field does not create the tag and immediately submits the form without checking if the required fields are empty or not

[max.txt](https://github.com/tovic/tags-input-beautifier/files/1053860/max.txt)

**Comment by tovic** [comment]
Fixed. See demo: https://tovic.github.io/tags-input-beautifier/tags-input-beautifier.escape.html
